repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.1
    hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
    - id: terraform_validate
      args:
        - --args=-json
        - --args=-no-color